server:
  port: 8080

spring:
  application:
    name: customer

  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/customer
    username: vncode
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true